name: test-dispatcher-filters
# run the workflow manually
on: [workflow_dispatch]
jobs:
  test_dispatcher_filters:
    # use lightweight Linux distro Alpine (https://hub.docker.com/_/alpine)
    container:
      image: alpine:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # install Apache (https://wiki.alpinelinux.org/wiki/Apache)
      - run: apk add apache2
      # create soft link "httpd" to "apache2"
      - run: ln -s /etc/apache2 /etc/httpd
      - run: mkdir -p /etc/httpd/conf.dispatcher.d/filters
      - run: mkdir -p /etc/httpd/modules/dispatcher
      - run: mkdir -p /var/www/renderer
      - run: cp dispatcher/mod_dispatcher.so /etc/httpd/modules/dispatcher/mod_dispatcher.so
      - run: cp httpd-dispatcher.conf /etc/httpd/conf.d/httpd-dispatcher.conf
      - run: cp dispatcher.any /etc/httpd/conf.dispatcher.d/dispatcher.any
      - run: ls -la /etc/httpd/*
      - run: cat /etc/httpd/conf.d/default.conf
      #- run: cp 02-dispatcher.conf /etc/httpd/conf.modules.d/02-dispatcher.conf
      - run: cp index.html /var/www/renderer/index.html
      # start Apache processes
      
      
      
      
      
